# AI-assisted schema markup creation

#### The plan:

- Crawl a website
- Select certain pages where we know their content and structure
- Determine the schema type and properties that can be found on those pages
- Send bulk requests to an LLM and get the structured data

## Import packages

In [ ]:
import os

import advertools as adv
import pandas as pd
from openai import OpenAI

pd.options.display.max_columns = None

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

## Crawl a website

In [ ]:
adv.crawl(
    url_list="https://searchnstuff.co.uk/",
    output_file="searchnstuff.jsonl",
    follow_links=True,
)

## Get the event URLs from the `searchnstuff.co.uk` website:

- Read the crawl file
- Split the URLs using `adv.url_to_df`

In [4]:
crawldf = pd.read_json("searchnstuff.jsonl", lines=True)
urldf = adv.url_to_df(crawldf["url"].str.replace(r"./", ""))
urldf.sample(10)

,url,scheme,netloc,path,query,fragment,dir_1,dir_2,last_dir
17,https://searchnstuff.co.uk/workshops/,https,searchnstuff.co.uk,/workshops/,None,None,workshops,None,workshops
21,https://searchnstuff.co.uk/networking-dinners/...,https,searchnstuff.co.uk,/networking-dinners/come-together-search-n-stu...,None,None,networking-dinners,come-together-search-n-stuff-community-christm...,come-together-search-n-stuff-community-christm...
22,https://searchnstuff.co.uk/meetups/search-n-st...,https,searchnstuff.co.uk,/meetups/search-n-stuff-london-meetup-event-hi...,None,None,meetups,search-n-stuff-london-meetup-event-highlights,search-n-stuff-london-meetup-event-highlights
10,https://searchnstuff.co.uk/join-us/,https,searchnstuff.co.uk,/join-us/,None,None,join-us,None,join-us
18,https://searchnstuff.co.uk/meetups/search-n-st...,https,searchnstuff.co.uk,/meetups/search-n-stuff-antalya-meetup-digital...,None,None,meetups,search-n-stuff-antalya-meetup-digital-marketin...,search-n-stuff-antalya-meetup-digital-marketin...
12,https://searchnstuff.co.uk/conferences/search-...,https,searchnstuff.co.uk,/conferences/search-n-stuff-antalya-conference...,None,None,conferences,search-n-stuff-antalya-conference-2024,search-n-stuff-antalya-conference-2024
9,https://searchnstuff.co.uk/about-us/,https,searchnstuff.co.uk,/about-us/,None,None,about-us,None,about-us
11,https://searchnstuff.co.uk/speakers-hub/,https,searchnstuff.co.uk,/speakers-hub/,None,None,speakers-hub,None,speakers-hub
4,https://searchnstuff.co.uk/privacy-policy/,https,searchnstuff.co.uk,/privacy-policy/,None,None,privacy-policy,None,privacy-policy
6,https://searchnstuff.co.uk/meetups/,https,searchnstuff.co.uk,/meetups/,None,None,meetups,None,meetups

## Find event pages
- Create a filter getting URLs where `dir_1` is in `["networking-dinners", "meetups", "conferences", "workshops"]`
- Save to a variable called `event_urls`

In [5]:
event_urls = urldf[
    urldf["dir_1"].isin(["networking-dinners", "meetups", "conferences", "workshops"])
    & urldf["dir_2"].notna()
]["url"].tolist()

In [6]:
event_urls

['https://searchnstuff.co.uk/conferences/search-n-stuff-antalya-conference-2025/',
 'https://searchnstuff.co.uk/conferences/search-n-stuff-antalya-conference-2024/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-london-meetup-in-partnership-with-semrush/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-istanbul-edition/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-london-meetup-summer-party-networking/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-antalya-meetup-digital-marketing-tips-startup-growth/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-london-meetup-in-partnership-with-studiohawk/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-x-podcast-growth-insights-strategies-and-real-stories/',
 'https://searchnstuff.co.uk/networking-dinners/come-together-search-n-stuff-community-christmas-dinner/',
 'https://searchnstuff.co.uk/meetups/search-n-stuff-london-meetup-event-highlights/']

## Create a function to generate JSON-LD

In [7]:
def generate_schema(crawl_df, schema_type, *properties):
    """Request the schema for a given crawl Dataframe, a schema type and any properties

    Parameters
    ----------
    crawl_df : pandas.DataFrame
        A crawl DataFrame generated from the advertools crawl function
    schema_type : str
        The schema.org type to use (Person, Organization, Event, etc.)
    properties : str
        One or more properties to extract from the given pages (price, currency, etc.)
    """
    responses = []
    for _, row in crawl_df.iterrows():
        completion = client.chat.completions.create(
            model="gpt-4o",
            temperature=0,
            seed=123,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": """
                You are an expert in structured data, especially JSON-LD, you respond in
                JSON only.
                You provide the details of the requested properties only.
                In case you cannot extract the requied data, you respond with `null`""",
                },
                {
                    "role": "user",
                    "content": f"""
        Please create the JSON-LD schema using the following details from the landing page:

        "@type": {schema_type}

        - required schema properties: {", ".join(properties)}

        - Details from landing page:

        HTML title: {row.get("title", "NOT AVAILABLE - PLEASE IGNORE")}
        HTML meta description: {row.get("meta_desc", "NOT AVAILABLE - PLEASE IGNORE")}
        HTML h1 tags: {row.get("h1", "NOT AVAILABLE - PLEASE IGNORE")}
        HTML h2 tags: {row.get("h2", "NOT AVAILABLE - PLEASE IGNORE")}
        HTML body text: {row.get("body_text", "NOT AVAILABLE - PLEASE IGNORE")}
        """,
                },
            ],
        )
        responses.append((row["url"], completion))
    return responses

In [8]:
event_df = crawldf[crawldf["url"].isin(event_urls)]

In [ ]:
responses = generate_schema(
    event_df,
    "BusinessEvent",
    "name",
    "description",
    "sartDate",
    "endDate",
    "organizer",
    "isAccessibleForFree",
    "location",
)

In [ ]:
import json

schema_df = pd.concat(
    [pd.json_normalize(json.loads(r[1].choices[0].message.content)) for r in responses]
)
schema_df.insert(0, "url", [r[0] for r in responses])
schema_df.to_csv("schema_df.csv", index=False)

In [11]:
schema_df = pd.read_csv("schema_df.csv")
schema_df

,url,@context,@type,name,description,startDate,endDate,isAccessibleForFree,organizer.@type,organizer.name,organizer.url,location.@type,location.name,location.address.@type,location.address.addressLocality,location.address.addressCountry,location.address.streetAddress,location.address.postalCode,location,location.address.addressRegion,location.address
0,https://searchnstuff.co.uk/conferences/search-...,https://schema.org,BusinessEvent,Search ‘n Stuff Antalya Global Digital Marketi...,Join us for a 5-Star Luxurious Learning & Netw...,2025-10-09,2025-10-12,False,Organization,Search 'n Stuff,https://searchnstuff.co.uk,Place,Baia Lara Hotel,PostalAddress,Antalya,Turkey,NaN,NaN,NaN,NaN,NaN
1,https://searchnstuff.co.uk/conferences/search-...,https://schema.org,BusinessEvent,Search ‘n Stuff Antalya Conference 2024,Welcome to the inaugural Search ‘n Stuff Confe...,NaN,NaN,NaN,Organization,Yagmur Simsek,NaN,Place,"Antalya, Turkey",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff London Meetup – in partnership...,Ready for something epic? We’re teaming up wit...,2024-03-18T19:00:00+00:00,2024-03-18T21:30:00+00:00,False,Organization,Search ‘n Stuff,https://www.linkedin.com/company/search-n-stuff/,Place,Paddington Works,PostalAddress,London,UK,8 Hermitage St,W2 1BE,NaN,NaN,NaN
3,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff Istanbul Edition,Search ‘n Stuff Istanbul Edition on October 15...,2023-10-15,2023-10-15,False,Organization,searchnstuff.co.uk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff London Meetup – Summer Party &...,"Get ready, London! The biggest Search ‘n Stuff...",2025-06-11T18:30:00+01:00,2025-06-11T22:00:00+01:00,False,Organization,Search ‘n Stuff,NaN,Place,Doggett’s Coat and Badge,PostalAddress,London,UK,NaN,NaN,NaN,NaN,NaN
5,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff Antalya Meetup – Digital Marke...,Antalya’s digital marketing and startup scene ...,2025-03-21T18:00:00+03:00,2025-03-21T22:00:00+03:00,False,Organization,Search 'n Stuff Community,NaN,Place,The Soul Antalya,PostalAddress,Muratpaşa,Turkey,Kılınçarslan Mh. Park Sk. No:36 Thesoul,07010,NaN,Antalya,NaN
6,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff London Meetup – in partnership...,Join us for our the first Search ‘n Stuff even...,2024-01-25T18:00:00+00:00,2024-01-25T21:30:00+00:00,False,Organization,Search ‘n Stuff,https://www.linkedin.com/company/search-n-stuff/,Place,Looking Glass Cocktail Club,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"49 Hackney Rd, Shoreditch, London"
7,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,"Search ‘n Stuff x Podcast Growth: Insights, St...",Join us for Search 'n Stuff x Podcast Growth E...,2025-01-15T18:30,2025-01-15T22:00,False,Organization,Search 'n Stuff,NaN,Place,Linden House,PostalAddress,London,UK,Hammersmith,W6 9TA,NaN,NaN,NaN
8,https://searchnstuff.co.uk/networking-dinners/...,https://schema.org,BusinessEvent,Come Together: Search ‘n Stuff Community Chris...,"As the year draws to a close, we're creating a...",2024-12-12T20:00:00,NaN,False,Organization,Search 'n Stuff,NaN,Place,The Counter Soho,PostalAddress,London,NaN,NaN,NaN,NaN,NaN,NaN
9,https://searchnstuff.co.uk/meetups/search-n-st...,https://schema.org,BusinessEvent,Search ‘n Stuff London Meetup – Event Highlights,The first Search ‘n Stuff meetup of 2024 on Ja...,2024-01-25,2024-01-25,False,Organization,Search ‘n Stuff,https://searchnstuff.co.uk,Place,London,PostalAddress,London,UK,NaN,NaN,NaN,NaN,NaN

In [ ]:
import plotly.express as px

fig = px.scatter(
    schema_df,
    x="startDate",
    y=[1 for i in range(len(schema_df))],
    hover_name="name",
    opacity=0.6,
    title="Search 'n Stuff Event Timeline",
    template="cosmo",
    hover_data=["name", "startDate"],
    height=350,
    custom_data=["name", "startDate"],
    size=[14 for i in range(len(schema_df))],
    labels={"startDate": "Event date"},
)
fig.layout.yaxis.visible = False
fig.data[0].hovertemplate = "<b>%{customdata[0]}</b><br><br>Date: %{customdata[1]}"

fig

## Formatting and structuring the inputs for the LLM

In [90]:
from IPython.display import display_markdown


def dm(text):
    return display_markdown(text, raw=True)


for _, row in crawldf[crawldf["url"].str.contains("2025")].iterrows():
    dm(f"#### **Title:** {row.title}")
    dm(f"#### **Meta description:** {row.meta_desc}")
    dm(f"#### **h1:** {row.h1}")
    dm(f"#### **h2:** {row.h2.split('@@')}")
    dm(f"#### **h3:** {row.h3.split('@@')}")
    dm(f"#### **h4:** {row.h4.split('@@')}")
    dm(f"#### **Body text:** {row.body_text[109:]}")

#### **Title:** Search 'n Stuff Antalya Global Digital Marketing Conference 2025 - searchnstuff.co.uk

#### **Meta description:** Search 'n Stuff Antalya Global Digital Marketing Conference 2025: Perfect for marketing enthusiasts, experts, innovators. Join us!

#### **h1:** Search ‘n Stuff Antalya Global Digital Marketing Conference 2025

#### **h2:** ['Your Digital Journey in Progress – Connect, Learn & Grow in a 5-Star Setting', 'Why Should You Be There?', 'What’s Included?', 'Secure Your Spot – Limited Tickets Available!', 'Conference Overview', 'Our Speakers (A-Z)', 'Our Sponsors', 'Calling All Sponsors – Amplify Your Brand with Search ‘n Stuff!', 'Why Should You Attend? Convince Your Manager or Colleagues!', 'Frequently Asked Questions', 'About the Venue', 'Subscribe to the newsletter to be the first to be informed!', 'About Us', 'Write An E-mail', 'Address']

#### **h3:** ['All Tickets Include', 'Early Bird Tickets – June 1, 2025 – July 31, 2025', 'Platinum Sponsors', 'Community Supporters', 'Media Partners', 'Workshop Sponsors', '\nRelated Posts']

#### **h4:** ['Conference Details', 'Simultaneous Translation', 'Transformative Knowledge', 'Unparalleled Networking', 'ExclusiveExperience', 'UnbeatableValue', 'Luxurious Accommodation', 'All-Inclusive Dining and Drinks', 'Conference and Workshops', 'Stunning Beachside Setting', 'Baia Lara Hotel', 'Search ‘n Stuff Antalya Conference 2024']

#### **Body text:**